"""PIC.md authoring + retrieval for the brand picture book.

PIC.md lives at ``{storage_dir}/brands/{brand_id}/PIC.md``. It is a real,
human-readable markdown file — `cat` it, edit it manually, version-control
it if you want. The file has two regions:

  1. Distilled style guide — generated by the planning model. Rewritten on
     ``/api/brand/pic/refresh``. Sections: Identity, Visual style, Palette,
     Subject language, Setting/environment, Forbidden, Competitive
     distinction, Reference anchors.
  2. Evolution log — append-only. ``append_lesson()`` adds dated one-liners
     under the trailing ``## Evolution log`` section. Survives refreshes
     (we copy it forward on regeneration so accumulated lessons are not
     wiped).

Every image-generation prompt builder calls ``load_pic(brand_id)`` and
prepends ``format_for_prompt(content)`` ahead of the call-specific prompt.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from app.config import settings
from app.services.llm.client import chat_json

log = logging.getLogger(__name__)

PIC_FILENAME = "PIC.md"

# Marker used to fence off the append-only evolution log so we can preserve
# it across refreshes without parsing markdown.
_EVOLUTION_LOG_HEADER = "## Evolution log"
_EVOLUTION_LOG_HINT = (
    "<!-- Append-only. Each entry: YYYY-MM-DD · source · lesson -->"
)


# ── PIC.md author schema (LLM output) ────────────────────────────────────
# We ask the LLM for structured fields and assemble the markdown
# deterministically so the file shape is stable regardless of how chatty
# the model gets. Each field is one to three concrete sentences.

_PIC_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "identity_summary": {"type": "string"},
        "visual_style": {"type": "string"},
        "palette_notes": {"type": "string"},
        "subject_language": {"type": "string"},
        "setting_environment": {"type": "string"},
        "forbidden": {"type": "string"},
        "competitive_distinction": {"type": "string"},
        "reference_anchors": {"type": "string"},
    },
    "required": [
        "identity_summary",
        "visual_style",
        "palette_notes",
        "subject_language",
        "setting_environment",
        "forbidden",
        "competitive_distinction",
        "reference_anchors",
    ],
}


def pic_path(brand_id: str) -> Path:
    """Resolve the on-disk PIC.md path for a brand. Caller is responsible
    for ensuring the parent directory exists when writing — `save_pic`
    handles that automatically."""
    return Path(settings.storage_dir) / "brands" / brand_id / PIC_FILENAME


def load_pic(brand_id: str) -> str | None:
    """Read the PIC.md file for a brand, or None if it doesn't exist yet."""
    if not brand_id:
        return None
    p = pic_path(brand_id)
    if not p.exists() or not p.is_file():
        return None
    try:
        return p.read_text(encoding="utf-8")
    except OSError as e:
        log.warning("pic load: failed to read %s: %s", p, e)
        return None


def save_pic(brand_id: str, content: str) -> Path:
    """Write the PIC.md file for a brand, creating parent dirs as needed."""
    p = pic_path(brand_id)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p


def _existing_evolution_log(content: str | None) -> str:
    """Carve out the ``## Evolution log`` section from a previous PIC.md
    so we can preserve appended lessons across a regeneration. Returns the
    log body (everything below the header line) or an empty string if no
    log section was found."""
    if not content:
        return ""
    idx = content.find(_EVOLUTION_LOG_HEADER)
    if idx < 0:
        return ""
    tail = content[idx + len(_EVOLUTION_LOG_HEADER):].strip("\n")
    # Strip the hint comment if present so it's not duplicated.
    if tail.startswith(_EVOLUTION_LOG_HINT):
        tail = tail[len(_EVOLUTION_LOG_HINT):].strip("\n")
    return tail


def _competitor_digest(brand: dict) -> str:
    """Compact one-paragraph summary of `reference_brands` so the LLM can
    reason about competitive distinction without us serializing the whole
    list. We highlight name, palette accents, and any voice excerpt — the
    visual hooks that matter for the picture book."""
    refs = brand.get("reference_brands") or []
    if not refs:
        return ""
    chunks: list[str] = []
    for r in refs[:5]:
        name = (r.get("name") or "").strip()
        if not name:
            continue
        palette = (r.get("palette") or [])[:3]
        excerpt = (r.get("voice_excerpt") or "").strip()
        bits = [f"name={name}"]
        if palette:
            bits.append(f"palette={','.join(palette)}")
        if excerpt:
            bits.append(f"excerpt={excerpt[:120]!r}")
        chunks.append("; ".join(bits))
    return " | ".join(chunks)


def _recent_posts_digest(brand: dict) -> str:
    """Strip recent_posts to a tiny digest — caption + visual_summary.
    Long captions or full transcripts get clipped because we just need a
    feel for what's been shipped."""
    posts = brand.get("recent_posts") or []
    chunks: list[str] = []
    for p in posts[:6]:
        cap = (p.get("caption") or "").strip()
        va = p.get("video_analysis") or {}
        vs = (va.get("visual_summary") or "").strip() if isinstance(va, dict) else ""
        if cap or vs:
            chunks.append(f"- caption: {cap[:140]} || visuals: {vs[:160]}")
    return "\n".join(chunks)


def _build_compose_messages(brand: dict) -> list[dict]:
    name = brand.get("name") or "the brand"
    description = (brand.get("description") or "").strip()
    palette = (brand.get("palette") or [])[:6]
    palette_str = ", ".join(palette) if palette else "(none provided)"
    style = brand.get("style_profile") or {}
    identity = brand.get("identity") or {}

    style_summary_bits: list[str] = []
    for k in (
        "mood",
        "composition",
        "photographic_vs_illustrated",
        "palette_character",
        "typography_feel",
    ):
        v = (style.get(k) or "").strip()
        if v:
            style_summary_bits.append(f"{k}: {v}")
    marks = style.get("distinctive_marks") or []
    if marks:
        style_summary_bits.append(f"distinctive_marks: {'; '.join(marks[:4])}")

    style_summary = ". ".join(style_summary_bits) or "(no style_profile yet)"
    competitor_digest = _competitor_digest(brand) or "(no reference brands)"
    recent_digest = _recent_posts_digest(brand) or "(no recent posts)"

    voice = brand.get("voice_profile") or {}
    voice_tone = (voice.get("tone") or "").strip() or "(no tone)"

    system = (
        "You are a brand creative director authoring a PICTURE BOOK — a "
        "compact, evergreen visual identity playbook the AI will consult on "
        "EVERY image-generation call (still keyframes, video clips, hero "
        "images, image edits, social posts). Your output gets prepended to "
        "every prompt. Optimize for being read by an image model, not by a "
        "human design committee.\n\n"
        "Each section is 1-3 SENTENCES of CONCRETE language: name lensing "
        "(35mm shallow DOF), name light direction (window key from camera-"
        "left), name treatment (Kodak Portra grade, warm shadows). Vague "
        "vibes ('modern', 'premium', 'cinematic') are forbidden. The image "
        "model needs nouns and verbs.\n\n"
        "Sections you must author:\n"
        "1. identity_summary — one sentence on what the brand IS, plus a "
        "   second sentence on the feeling its imagery should evoke.\n"
        "2. visual_style — concrete lens + lighting + treatment vocabulary "
        "   (focal length, key/fill direction, grade, contrast).\n"
        "3. palette_notes — how the brand's colors are USED (background "
        "   dominant? accents? skin-tone bias?). Reference the hex list "
        "   provided to you, do not invent new colors.\n"
        "4. subject_language — how people, products, and props are SHOT "
        "   (3/4 portraits? overhead product? hands-only?). Cast posture, "
        "   wardrobe, expression defaults.\n"
        "5. setting_environment — where shots take place (interior moods, "
        "   architectural eras, locations the brand favors).\n"
        "6. forbidden — explicit anti-list. ALWAYS include AI-stock-photo "
        "   gloss, generic corporate handshakes, fake-creator AI faces, "
        "   rainbow gradients, shiny chrome 3D, UI overlays, baked-in text. "
        "   Add brand-specific don'ts.\n"
        "7. competitive_distinction — what reference brands do well that we "
        "   borrow ENERGY from (not compositions), and the ONE thing that "
        "   makes our imagery distinguishable from theirs.\n"
        "8. reference_anchors — 2-4 named touchstones (filmmakers, "
        "   photographers, campaigns, periodicals). Concrete names, not "
        "   genres.\n\n"
        "Output JSON only with the eight string fields above."
    )

    user_lines: list[str] = [
        f"Brand: {name}",
    ]
    if description:
        user_lines.append(f"Description: {description}")
    user_lines.append(f"Voice tone: {voice_tone}")
    user_lines.append(f"Brand palette (hex): {palette_str}")
    user_lines.append(f"Style profile signals: {style_summary}")
    if identity:
        # Just a hint that the brand has typography/identity tokens — the
        # full identity dict is too noisy for the picture book.
        typo = (identity.get("typography") or {}) if isinstance(identity, dict) else {}
        h_font = (typo.get("headline_font") if isinstance(typo, dict) else None) or ""
        b_font = (typo.get("body_font") if isinstance(typo, dict) else None) or ""
        if h_font or b_font:
            user_lines.append(
                f"Brand typography (informs subject_language only): "
                f"headline={h_font!r}, body={b_font!r}"
            )
    user_lines.append(f"Reference brands (for competitive_distinction):\n{competitor_digest}")
    user_lines.append(f"Recent posts digest (for visual_style + subject_language):\n{recent_digest}")

    return [
        {"role": "system", "content": system},
        {"role": "user", "content": "\n".join(user_lines)},
    ]


def _assemble_markdown(
    brand: dict,
    sections: dict,
    evolution_log: str = "",
) -> str:
    """Deterministic markdown layout from the LLM's structured sections.

    Always renders the same shape so downstream prompt-builders can rely on
    section ordering. Evolution log is preserved verbatim from prior content
    when this is a regeneration.
    """
    name = brand.get("name") or "the brand"
    palette = (brand.get("palette") or [])[:8]
    palette_line = ", ".join(palette) if palette else "(no palette set)"
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    def s(key: str) -> str:
        return (sections.get(key) or "").strip() or "_(not yet authored)_"

    body = f"""# PIC.md — {name}

> The brand picture book. Generated {today}. Read by every image-generation
> call (keyframes, ingredients, Veo clips, image edits, hero images, social
> posts) so all visuals cohere on one identity. Refresh via
> `POST /api/brand/pic/refresh`. Append a lesson via
> `POST /api/brand/pic/lesson`.

## Identity

{s("identity_summary")}

## Visual style

{s("visual_style")}

## Palette & color use

{s("palette_notes")}

**Hex anchors:** {palette_line}

## Subject language

{s("subject_language")}

## Setting / environment

{s("setting_environment")}

## Forbidden — never produce these

{s("forbidden")}

## Competitive distinction

{s("competitive_distinction")}

## Reference anchors

{s("reference_anchors")}

{_EVOLUTION_LOG_HEADER}

{_EVOLUTION_LOG_HINT}
"""
    log_body = (evolution_log or "").strip()
    if log_body:
        body = body + "\n" + log_body + "\n"
    return body


async def compose_pic(brand: dict, *, preserve_log: bool = True) -> str:
    """Run the planning model to author PIC.md sections, then assemble.

    When ``preserve_log`` is True (default) we read the existing PIC.md
    (if any) and carry the Evolution log section forward into the new
    file so accumulated lessons survive a refresh.
    """
    brand_id = str(brand.get("id") or "").strip()
    if not brand_id:
        raise ValueError("compose_pic: brand has no id")

    messages = _build_compose_messages(brand)
    sections = await chat_json(
        messages,
        schema=_PIC_SCHEMA,
        model=settings.gemini_planning_model,
    )

    log_section = ""
    if preserve_log:
        existing = load_pic(brand_id)
        log_section = _existing_evolution_log(existing)

    return _assemble_markdown(brand, sections, evolution_log=log_section)


async def ensure_pic(brand: dict) -> str:
    """Return PIC.md for a brand, generating + saving it if missing."""
    brand_id = str(brand.get("id") or "").strip()
    if not brand_id:
        raise ValueError("ensure_pic: brand has no id")
    existing = load_pic(brand_id)
    if existing:
        return existing
    content = await compose_pic(brand, preserve_log=False)
    save_pic(brand_id, content)
    return content


def append_lesson(
    brand_id: str, lesson: str, source: str = "user"
) -> str | None:
    """Append a one-line lesson under the Evolution log section.

    Returns the updated file content, or None if no PIC.md exists for the
    brand yet (caller should ensure_pic first). The lesson is prefixed with
    today's date and the source so the log self-documents over time.
    """
    content = load_pic(brand_id)
    if content is None:
        return None
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    line = f"- {today} · {source} · {lesson.strip()}".rstrip()

    # Ensure the log header exists; if a hand-edit dropped it, re-add.
    if _EVOLUTION_LOG_HEADER not in content:
        content = content.rstrip() + (
            f"\n\n{_EVOLUTION_LOG_HEADER}\n\n{_EVOLUTION_LOG_HINT}\n"
        )
    # Append the lesson line at the end of the file.
    if not content.endswith("\n"):
        content = content + "\n"
    content = content + line + "\n"
    save_pic(brand_id, content)
    return content


def format_for_prompt(content: str | None) -> str:
    """Render PIC.md as a compact prefix block for image-gen prompts.

    We strip the markdown headings/quotes and keep the body text only —
    image models don't care about the markdown chrome but DO care about
    the rules. Cap at ~2000 chars so we don't displace the per-call
    instructions in tight context windows.
    """
    if not content:
        return ""
    # Drop the ``## Evolution log`` section from the prompt-side view —
    # it's a journal for humans, not a directive for the image model.
    log_idx = content.find(_EVOLUTION_LOG_HEADER)
    if log_idx >= 0:
        content = content[:log_idx]

    lines: list[str] = []
    for raw in content.splitlines():
        ln = raw.rstrip()
        if not ln:
            continue
        # Strip markdown atx headers and blockquote prefixes; we keep the
        # text so section labels still anchor the rules.
        if ln.startswith(">"):
            continue
        if ln.startswith("# "):
            continue  # title — already implied by the surrounding directive
        if ln.startswith("## "):
            lines.append(ln[3:].strip().upper() + ":")
            continue
        lines.append(ln)
    body = " ".join(lines).strip()
    if len(body) > 2000:
        body = body[:1997] + "..."
    if not body:
        return ""
    return (
        "BRAND PICTURE BOOK — every image must conform to this evergreen "
        "visual identity. " + body
    )
