"""Brand-level endpoints — currently scoped to the picture book (PIC.md).

PIC.md is the evergreen visual identity playbook generated by the planning
model and read by every image-generation call. Three routes:

  - GET  /api/brand/pic           — return the latest brand's PIC.md as
                                    text/markdown (auto-generates if missing)
  - POST /api/brand/pic/refresh   — regenerate PIC.md from current brand
                                    state (preserves the Evolution log)
  - POST /api/brand/pic/lesson    — append a one-line lesson to the
                                    Evolution log section
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field

from app.db import models
from app.db.session import SessionLocal
from app.events.bus import bus
from app.events.types import Events
from app.services.brand_book import (
    append_lesson,
    compose_pic,
    ensure_pic,
    load_pic,
    save_pic,
)

log = logging.getLogger(__name__)

router = APIRouter(prefix="/brand")


def _load_latest_brand_dict() -> dict | None:
    """Snapshot the most-recently-onboarded brand in the shape PIC composer
    expects. Mirrors the pattern in storyboard.py + video.py so the brand
    record is always read the same way across surfaces."""
    with SessionLocal() as db:
        b = (
            db.query(models.Brand)
            .filter(models.Brand.onboarded_at.is_not(None))
            .order_by(models.Brand.onboarded_at.desc())
            .first()
        )
        if b is None:
            return None
        return {
            "id": b.id,
            "name": b.name,
            "url": b.url,
            "description": b.description,
            "voice_profile": b.voice_profile,
            "palette": b.palette,
            "palette_roles": b.palette_roles,
            "identity": b.identity,
            "style_profile": b.style_profile,
            "recent_posts": b.recent_posts or [],
            "reference_brands": b.reference_brands or [],
            "assets": b.assets or [],
            "handles": b.handles or {},
        }


@router.get("/pic", response_class=PlainTextResponse)
async def get_pic() -> str:
    """Return PIC.md for the latest brand. Generates it on first request if
    no file exists yet. Returns text/markdown so curl + the browser can show
    it directly without JSON unwrapping."""
    brand = _load_latest_brand_dict()
    if brand is None:
        raise HTTPException(status_code=409, detail="no onboarded brand")

    existing = load_pic(brand["id"])
    if existing:
        return existing

    # First-touch generation: emit the lifecycle events so the frontend can
    # show progress instead of a stalled GET.
    bus.emit(
        Events.BRAND_PIC_GENERATING,
        {"brand_id": brand["id"], "trigger": "first_read"},
    )
    try:
        content = await compose_pic(brand, preserve_log=False)
    except Exception as e:
        log.exception("brand.pic compose failed: %s", e)
        raise HTTPException(
            status_code=502, detail=f"pic compose failed: {e}"
        ) from e
    save_pic(brand["id"], content)
    bus.emit(
        Events.BRAND_PIC_GENERATED,
        {
            "brand_id": brand["id"],
            "trigger": "first_read",
            "char_count": len(content),
        },
    )
    return content


class RefreshOut(BaseModel):
    brand_id: str
    char_count: int


@router.post("/pic/refresh", response_model=RefreshOut)
async def post_refresh() -> RefreshOut:
    """Regenerate PIC.md for the latest brand. Preserves the Evolution log
    section so accumulated lessons survive a refresh."""
    brand = _load_latest_brand_dict()
    if brand is None:
        raise HTTPException(status_code=409, detail="no onboarded brand")

    bus.emit(
        Events.BRAND_PIC_GENERATING,
        {"brand_id": brand["id"], "trigger": "refresh"},
    )
    try:
        content = await compose_pic(brand, preserve_log=True)
    except Exception as e:
        log.exception("brand.pic refresh failed: %s", e)
        raise HTTPException(
            status_code=502, detail=f"pic refresh failed: {e}"
        ) from e
    save_pic(brand["id"], content)
    bus.emit(
        Events.BRAND_PIC_GENERATED,
        {
            "brand_id": brand["id"],
            "trigger": "refresh",
            "char_count": len(content),
        },
    )
    return RefreshOut(brand_id=brand["id"], char_count=len(content))


class LessonIn(BaseModel):
    lesson: str = Field(..., min_length=3, max_length=400)
    source: str = Field(default="user", max_length=60)


class LessonOut(BaseModel):
    brand_id: str
    char_count: int


@router.post("/pic/lesson", response_model=LessonOut)
async def post_lesson(body: LessonIn) -> LessonOut:
    """Append a dated one-liner to the Evolution log. Use this when an
    image worked or failed in a non-obvious way and the picture book
    should remember why."""
    brand = _load_latest_brand_dict()
    if brand is None:
        raise HTTPException(status_code=409, detail="no onboarded brand")

    # Ensure PIC exists before appending — we don't want a lesson written
    # to a vacuum.
    try:
        await ensure_pic(brand)
    except Exception as e:
        log.exception("brand.pic ensure failed: %s", e)
        raise HTTPException(
            status_code=502, detail=f"pic ensure failed: {e}"
        ) from e

    updated = append_lesson(brand["id"], body.lesson, source=body.source)
    if updated is None:
        # ensure_pic should have created it; this is a real failure.
        raise HTTPException(status_code=502, detail="pic file unavailable")

    bus.emit(
        Events.BRAND_PIC_LESSON_APPENDED,
        {
            "brand_id": brand["id"],
            "lesson": body.lesson,
            "source": body.source,
        },
    )
    return LessonOut(brand_id=brand["id"], char_count=len(updated))
